# If the user's terminal is in dark mode, Yazi will load `theme-dark.toml` on startup; otherwise, `theme-light.toml`.
# You can override any parts of them that are not related to the dark/light mode in your own `theme.toml`.

# If you want to dynamically override their content based on dark/light mode, you can specify two different flavors
# for dark and light modes under `[flavor]`, and do so in those flavors instead.
"$schema" = "https://yazi-rs.github.io/schemas/theme.json"

# vim:fileencoding=utf-8:foldmethod=marker

# : Flavor {{{

[flavor]
dark  = ""
light = ""

# : }}}


# : Manager {{{

[manager]
cwd = { fg = "cyan" }

# Hovered
hovered         = { reversed = true }
preview_hovered = { underline = true }

# Find
find_keyword  = { fg = "yellow", bold = true, italic = true, underline = true }
find_position = { fg = "magenta", bg = "reset", bold = true, italic = true }

# Marker
marker_copied   = { fg = "lightgreen",  bg = "lightgreen" }
marker_cut      = { fg = "lightred",    bg = "lightred" }
marker_marked   = { fg = "lightcyan",   bg = "lightcyan" }
marker_selected = { fg = "lightyellow", bg = "lightyellow" }

# Tab
tab_active   = { reversed = true }
tab_inactive = {}
tab_width    = 1

# Count
count_copied   = { fg = "white", bg = "green" }
count_cut      = { fg = "white", bg = "red" }
count_selected = { fg = "white", bg = "yellow" }

# Border
border_symbol = "│"
border_style  = { fg = "gray" }

# Highlighting
syntect_theme = ""

# : }}}


# : Mode {{{

[mode]

normal_main = { bg = "blue", bold = true }
normal_alt  = { fg = "blue", bg = "gray" }

# Select mode
select_main = { bg = "red", bold = true }
select_alt  = { fg = "red", bg = "gray" }

# Unset mode
unset_main = { bg = "red", bold = true }
unset_alt  = { fg = "red", bg = "gray" }

# : }}}


# : Status bar {{{

[status]
separator_open  = ""
separator_close = ""

# Progress
progress_label  = { bold = true }
progress_normal = { fg = "blue", bg = "black" }
progress_error  = { fg = "red", bg = "black" }

# Permissions
perm_sep   = { fg = "darkgray" }
perm_type  = { fg = "green" }
perm_read  = { fg = "yellow" }
perm_write = { fg = "red" }
perm_exec  = { fg = "cyan" }

# : }}}


# : Which {{{

[which]
cols            = 3
mask            = { bg = "black" }
cand            = { fg = "lightcyan" }
rest            = { fg = "darkgray" }
desc            = { fg = "lightmagenta" }
separator       = "  "
separator_style = { fg = "darkgray" }

# : }}}


# : Confirmation {{{

[confirm]
border     = { fg = "blue" }
title      = { fg = "blue" }
content    = {}
list       = {}
btn_yes    = { reversed = true }
btn_no     = {}
btn_labels = [ "  [Y]es  ", "  (N)o  " ]

# : }}}


# : Spotter {{{

[spot]
border = { fg = "blue" }
title  = { fg = "blue" }

# : }}}


# : Notification {{{

[notify]
title_info  = { fg = "green" }
title_warn  = { fg = "yellow" }
title_error = { fg = "red" }

# Icons
icon_info  = ""
icon_warn  = ""
icon_error = ""

# : }}}


# : Picker {{{

[pick]
border   = { fg = "blue" }
active   = { fg = "magenta", bold = true }
inactive = {}

# : }}}


# : Input {{{

[input]
border   = { fg = "blue" }
title    = {}
value    = {}
selected = { reversed = true }

# : }}}


# : Completion {{{

[completion]
border   = { fg = "blue" }
active   = { reversed = true }
inactive = {}

# Icons
icon_file    = ""
icon_folder  = ""
icon_command = ""

# : }}}


# : Task manager {{{

[tasks]
border  = { fg = "blue" }
title   = {}
hovered = { fg = "magenta", underline = true }

# : }}}


# : Help menu {{{

[help]
on      = { fg = "cyan" }
run     = { fg = "magenta" }
desc    = {}
hovered = { reversed = true, bold = true }
footer  = { fg = "black", bg = "white" }

# : }}}


# : File-specific styles {{{

[filetype]

rules = [
	# Images
	{ mime = "image/*", fg = "yellow" },

	# Media
	{ mime = "{audio,video}/*", fg = "magenta" },

	# Archives
	{ mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "red" },

	# Documents
	{ mime = "application/{pdf,doc,rtf}", fg = "cyan" },

	# Empty files
	# { mime = "inode/empty", fg = "red" },

	# Special files
	{ name = "*", is = "orphan", bg = "red" },
	{ name = "*", is = "exec"  , fg = "green" },

	# Dummy files
	{ name = "*", is = "dummy", bg = "red" },
	{ name = "*/", is = "dummy", bg = "red" },

	# Fallback
	# { name = "*", fg = "white" },
	{ name = "*/", fg = "blue" }
]

# : }}}


# : Icons {{{

[icon]

globs = []
dirs  = [
	{ name = ".config", text = "" },
	{ name = ".git", text = "" },
	{ name = ".github", text = "" },
	{ name = ".npm", text = "" },
	{ name = "Desktop", text = "" },
	{ name = "Development", text = "" },
	{ name = "Documents", text = "" },
	{ name = "Downloads", text = "" },
	{ name = "Library", text = "" },
	{ name = "Movies", text = "" },
	{ name = "Music", text = "" },
	{ name = "Pictures", text = "" },
	{ name = "Public", text = "" },
	{ name = "Videos", text = "" },
]
files = [
	{ name = ".babelrc", text = "", fg = "#cbcb41" },
	{ name = ".bash_profile", text = "", fg = "#89e051" },
	{ name = ".bashrc", text = "", fg = "#89e051" },
	{ name = ".clang-format", text = "", fg = "#6d8086" },
	{ name = ".clang-tidy", text = "", fg = "#6d8086" },
	{ name = ".codespellrc", text = "󰓆", fg = "#35da60" },
	{ name = ".condarc", text = "", fg = "#43b02a" },
	{ name = ".dockerignore", text = "󰡨", fg = "#458ee6" },
	{ name = ".ds_store", text = "", fg = "#41535b" },
	{ name = ".editorconfig", text = "", fg = "#fff2f2" },
	{ name = ".env", text = "", fg = "#faf743" },
	{ name = ".eslintignore", text = "", fg = "#4b32c3" },
	{ name = ".eslintrc", text = "", fg = "#4b32c3" },
	{ name = ".git-blame-ignore-revs", text = "", fg = "#f54d27" },
	{ name = ".gitattributes", text = "", fg = "#f54d27" },
	{ name = ".gitconfig", text = "", fg = "#f54d27" },
	{ name = ".gitignore", text = "", fg = "#f54d27" },
	{ name = ".gitlab-ci.yml", text = "", fg = "#e24329" },
	{ name = ".gitmodules", text = "", fg = "#f54d27" },
	{ name = ".gtkrc-2.0", text = "", fg = "#ffffff" },
	{ name = ".gvimrc", text = "", fg = "#019833" },
	{ name = ".justfile", text = "", fg = "#6d8086" },
	{ name = ".luacheckrc", text = "", fg = "#00a2ff" },
	{ name = ".luaurc", text = "", fg = "#00a2ff" },
	{ name = ".mailmap", text = "󰊢", fg = "#f54d27" },
	{ name = ".nanorc", text = "", fg = "#440077" },
	{ name = ".npmignore", text = "", fg = "#e8274b" },
	{ name = ".npmrc", text = "", fg = "#e8274b" },
	{ name = ".nuxtrc", text = "󱄆", fg = "#00c58e" },
	{ name = ".nvmrc", text = "", fg = "#5fa04e" },
	{ name = ".pre-commit-config.yaml", text = "󰛢", fg = "#f8b424" },
	{ name = ".prettierignore", text = "", fg = "#4285f4" },
	{ name = ".prettierrc", text = "", fg = "#4285f4" },
	{ name = ".prettierrc.cjs", text = "", fg = "#4285f4" },
	{ name = ".prettierrc.js", text = "", fg = "#4285f4" },
	{ name = ".prettierrc.json", text = "", fg = "#4285f4" },
	{ name = ".prettierrc.json5", text = "", fg = "#4285f4" },
	{ name = ".prettierrc.mjs", text = "", fg = "#4285f4" },
	{ name = ".prettierrc.toml", text = "", fg = "#4285f4" },
	{ name = ".prettierrc.yaml", text = "", fg = "#4285f4" },
	{ name = ".prettierrc.yml", text = "", fg = "#4285f4" },
	{ name = ".pylintrc", text = "", fg = "#6d8086" },
	{ name = ".settings.json", text = "", fg = "#854cc7" },
	{ name = ".SRCINFO", text = "󰣇", fg = "#0f94d2" },
	{ name = ".vimrc", text = "", fg = "#019833" },
	{ name = ".Xauthority", text = "", fg = "#e54d18" },
	{ name = ".xinitrc", text = "", fg = "#e54d18" },
	{ name = ".Xresources", text = "", fg = "#e54d18" },
	{ name = ".xsession", text = "", fg = "#e54d18" },
	{ name = ".zprofile", text = "", fg = "#89e051" },
	{ name = ".zshenv", text = "", fg = "#89e051" },
	{ name = ".zshrc", text = "", fg = "#89e051" },
	{ name = "_gvimrc", text = "", fg = "#019833" },
	{ name = "_vimrc", text = "", fg = "#019833" },
	{ name = "AUTHORS", text = "", fg = "#a172ff" },
	{ name = "AUTHORS.txt", text = "", fg = "#a172ff" },
	{ name = "brewfile", text = "", fg = "#701516" },
	{ name = "bspwmrc", text = "", fg = "#2f2f2f" },
	{ name = "build", text = "", fg = "#89e051" },
	{ name = "build.gradle", text = "", fg = "#005f87" },
	{ name = "build.zig.zon", text = "", fg = "#f69a1b" },
	{ name = "bun.lockb", text = "", fg = "#eadcd1" },
	{ name = "cantorrc", text = "", fg = "#1c99f3" },
	{ name = "checkhealth", text = "󰓙", fg = "#75b4fb" },
	{ name = "cmakelists.txt", text = "", fg = "#dce3eb" },
	{ name = "code_of_conduct", text = "", fg = "#e41662" },
	{ name = "code_of_conduct.md", text = "", fg = "#e41662" },
	{ name = "commit_editmsg", text = "", fg = "#f54d27" },
	{ name = "commitlint.config.js", text = "󰜘", fg = "#2b9689" },
	{ name = "commitlint.config.ts", text = "󰜘", fg = "#2b9689" },
	{ name = "compose.yaml", text = "󰡨", fg = "#458ee6" },
	{ name = "compose.yml", text = "󰡨", fg = "#458ee6" },
	{ name = "config", text = "", fg = "#6d8086" },
	{ name = "containerfile", text = "󰡨", fg = "#458ee6" },
	{ name = "copying", text = "", fg = "#cbcb41" },
	{ name = "copying.lesser", text = "", fg = "#cbcb41" },
	{ name = "Directory.Build.props", text = "", fg = "#00a2ff" },
	{ name = "Directory.Build.targets", text = "", fg = "#00a2ff" },
	{ name = "Directory.Packages.props", text = "", fg = "#00a2ff" },
	{ name = "docker-compose.yaml", text = "󰡨", fg = "#458ee6" },
	{ name = "docker-compose.yml", text = "󰡨", fg = "#458ee6" },
	{ name = "dockerfile", text = "󰡨", fg = "#458ee6" },
	{ name = "eslint.config.cjs", text = "", fg = "#4b32c3" },
	{ name = "eslint.config.js", text = "", fg = "#4b32c3" },
	{ name = "eslint.config.mjs", text = "", fg = "#4b32c3" },
	{ name = "eslint.config.ts", text = "", fg = "#4b32c3" },
	{ name = "ext_typoscript_setup.txt", text = "", fg = "#ff8700" },
	{ name = "favicon.ico", text = "", fg = "#cbcb41" },
	{ name = "fp-info-cache", text = "", fg = "#ffffff" },
	{ name = "fp-lib-table", text = "", fg = "#ffffff" },
	{ name = "FreeCAD.conf", text = "", fg = "#cb333b" },
	{ name = "Gemfile", text = "", fg = "#701516" },
	{ name = "gnumakefile", text = "", fg = "#6d8086" },
	{ name = "go.mod", text = "", fg = "#519aba" },
	{ name = "go.sum", text = "", fg = "#519aba" },
	{ name = "go.work", text = "", fg = "#519aba" },
	{ name = "gradle-wrapper.properties", text = "", fg = "#005f87" },
	{ name = "gradle.properties", text = "", fg = "#005f87" },
	{ name = "gradlew", text = "", fg = "#005f87" },
	{ name = "groovy", text = "", fg = "#4a687c" },
	{ name = "gruntfile.babel.js", text = "", fg = "#e37933" },
	{ name = "gruntfile.coffee", text = "", fg = "#e37933" },
	{ name = "gruntfile.js", text = "", fg = "#e37933" },
	{ name = "gruntfile.ts", text = "", fg = "#e37933" },
	{ name = "gtkrc", text = "", fg = "#ffffff" },
	{ name = "gulpfile.babel.js", text = "", fg = "#cc3e44" },
	{ name = "gulpfile.coffee", text = "", fg = "#cc3e44" },
	{ name = "gulpfile.js", text = "", fg = "#cc3e44" },
	{ name = "gulpfile.ts", text = "", fg = "#cc3e44" },
	{ name = "hypridle.conf", text = "", fg = "#00aaae" },
	{ name = "hyprland.conf", text = "", fg = "#00aaae" },
	{ name = "hyprlock.conf", text = "", fg = "#00aaae" },
	{ name = "hyprpaper.conf", text = "", fg = "#00aaae" },
	{ name = "i18n.config.js", text = "󰗊", fg = "#7986cb" },
	{ name = "i18n.config.ts", text = "󰗊", fg = "#7986cb" },
	{ name = "i3blocks.conf", text = "", fg = "#e8ebee" },
	{ name = "i3status.conf", text = "", fg = "#e8ebee" },
	{ name = "index.theme", text = "", fg = "#2db96f" },
	{ name = "ionic.config.json", text = "", fg = "#4f8ff7" },
	{ name = "justfile", text = "", fg = "#6d8086" },
	{ name = "kalgebrarc", text = "", fg = "#1c99f3" },
	{ name = "kdeglobals", text = "", fg = "#1c99f3" },
	{ name = "kdenlive-layoutsrc", text = "", fg = "#83b8f2" },
	{ name = "kdenliverc", text = "", fg = "#83b8f2" },
	{ name = "kritadisplayrc", text = "", fg = "#f245fb" },
	{ name = "kritarc", text = "", fg = "#f245fb" },
	{ name = "license", text = "", fg = "#d0bf41" },
	{ name = "license.md", text = "", fg = "#d0bf41" },
	{ name = "lxde-rc.xml", text = "", fg = "#909090" },
	{ name = "lxqt.conf", text = "", fg = "#0192d3" },
	{ name = "makefile", text = "", fg = "#6d8086" },
	{ name = "mix.lock", text = "", fg = "#a074c4" },
	{ name = "mpv.conf", text = "", fg = "#3b1342" },
	{ name = "node_modules", text = "", fg = "#e8274b" },
	{ name = "nuxt.config.cjs", text = "󱄆", fg = "#00c58e" },
	{ name = "nuxt.config.js", text = "󱄆", fg = "#00c58e" },
	{ name = "nuxt.config.mjs", text = "󱄆", fg = "#00c58e" },
	{ name = "nuxt.config.ts", text = "󱄆", fg = "#00c58e" },
	{ name = "package-lock.json", text = "", fg = "#7a0d21" },
	{ name = "package.json", text = "", fg = "#e8274b" },
	{ name = "PKGBUILD", text = "", fg = "#0f94d2" },
	{ name = "platformio.ini", text = "", fg = "#f6822b" },
	{ name = "pom.xml", text = "", fg = "#7a0d21" },
	{ name = "prettier.config.cjs", text = "", fg = "#4285f4" },
	{ name = "prettier.config.js", text = "", fg = "#4285f4" },
	{ name = "prettier.config.mjs", text = "", fg = "#4285f4" },
	{ name = "prettier.config.ts", text = "", fg = "#4285f4" },
	{ name = "procfile", text = "", fg = "#a074c4" },
	{ name = "PrusaSlicer.ini", text = "", fg = "#ec6b23" },
	{ name = "PrusaSlicerGcodeViewer.ini", text = "", fg = "#ec6b23" },
	{ name = "py.typed", text = "", fg = "#ffbc03" },
	{ name = "QtProject.conf", text = "", fg = "#40cd52" },
	{ name = "rakefile", text = "", fg = "#701516" },
	{ name = "readme", text = "󰂺", fg = "#ededed" },
	{ name = "readme.md", text = "󰂺", fg = "#ededed" },
	{ name = "rmd", text = "", fg = "#519aba" },
	{ name = "robots.txt", text = "󰚩", fg = "#5d7096" },
	{ name = "security", text = "󰒃", fg = "#bec4c9" },
	{ name = "security.md", text = "󰒃", fg = "#bec4c9" },
	{ name = "settings.gradle", text = "", fg = "#005f87" },
	{ name = "svelte.config.js", text = "", fg = "#ff3e00" },
	{ name = "sxhkdrc", text = "", fg = "#2f2f2f" },
	{ name = "sym-lib-table", text = "", fg = "#ffffff" },
	{ name = "tailwind.config.js", text = "󱏿", fg = "#20c2e3" },
	{ name = "tailwind.config.mjs", text = "󱏿", fg = "#20c2e3" },
	{ name = "tailwind.config.ts", text = "󱏿", fg = "#20c2e3" },
	{ name = "tmux.conf", text = "", fg = "#14ba19" },
	{ name = "tmux.conf.local", text = "", fg = "#14ba19" },
	{ name = "tsconfig.json", text = "", fg = "#519aba" },
	{ name = "unlicense", text = "", fg = "#d0bf41" },
	{ name = "vagrantfile", text = "", fg = "#1563ff" },
	{ name = "vercel.json", text = "", fg = "#ffffff" },
	{ name = "vlcrc", text = "󰕼", fg = "#ee7a00" },
	{ name = "webpack", text = "󰜫", fg = "#519aba" },
	{ name = "weston.ini", text = "", fg = "#ffbb01" },
	{ name = "workspace", text = "", fg = "#89e051" },
	{ name = "xmobarrc", text = "", fg = "#fd4d5d" },
	{ name = "xmobarrc.hs", text = "", fg = "#fd4d5d" },
	{ name = "xmonad.hs", text = "", fg = "#fd4d5d" },
	{ name = "xorg.conf", text = "", fg = "#e54d18" },
	{ name = "xsettingsd.conf", text = "", fg = "#e54d18" },
]
exts = [
	{ name = "3gp", text = "", fg = "#fd971f" },
	{ name = "3mf", text = "󰆧", fg = "#888888" },
	{ name = "7z", text = "", fg = "#eca517" },
	{ name = "a", text = "", fg = "#dcddd6" },
	{ name = "aac", text = "", fg = "#00afff" },
	{ name = "adb", text = "", fg = "#22ffff" },
	{ name = "ads", text = "", fg = "#ffffff" },
	{ name = "ai", text = "", fg = "#cbcb41" },
	{ name = "aif", text = "", fg = "#00afff" },
	{ name = "aiff", text = "", fg = "#00afff" },
	{ name = "android", text = "", fg = "#34a853" },
	{ name = "ape", text = "", fg = "#00afff" },
	{ name = "apk", text = "", fg = "#34a853" },
	{ name = "apl", text = "", fg = "#24a148" },
	{ name = "app", text = "", fg = "#9f0500" },
	{ name = "applescript", text = "", fg = "#6d8085" },
	{ name = "asc", text = "󰦝", fg = "#576d7f" },
	{ name = "asm", text = "", fg = "#0091bd" },
	{ name = "ass", text = "󰨖", fg = "#ffb713" },
	{ name = "astro", text = "", fg = "#e23f67" },
	{ name = "avif", text = "", fg = "#a074c4" },
	{ name = "awk", text = "", fg = "#4d5a5e" },
	{ name = "azcli", text = "", fg = "#0078d4" },
	{ name = "bak", text = "󰁯", fg = "#6d8086" },
	{ name = "bash", text = "", fg = "#89e051" },
	{ name = "bat", text = "", fg = "#c1f12e" },
	{ name = "bazel", text = "", fg = "#89e051" },
	{ name = "bib", text = "󱉟", fg = "#cbcb41" },
	{ name = "bicep", text = "", fg = "#519aba" },
	{ name = "bicepparam", text = "", fg = "#9f74b3" },
	{ name = "bin", text = "", fg = "#9f0500" },
	{ name = "blade.php", text = "", fg = "#f05340" },
	{ name = "blend", text = "󰂫", fg = "#ea7600" },
	{ name = "blp", text = "󰺾", fg = "#5796e2" },
	{ name = "bmp", text = "", fg = "#a074c4" },
	{ name = "bqn", text = "", fg = "#24a148" },
	{ name = "brep", text = "󰻫", fg = "#839463" },
	{ name = "bz", text = "", fg = "#eca517" },
	{ name = "bz2", text = "", fg = "#eca517" },
	{ name = "bz3", text = "", fg = "#eca517" },
	{ name = "bzl", text = "", fg = "#89e051" },
	{ name = "c", text = "", fg = "#599eff" },
	{ name = "c++", text = "", fg = "#f34b7d" },
	{ name = "cache", text = "", fg = "#ffffff" },
	{ name = "cast", text = "", fg = "#fd971f" },
	{ name = "cbl", text = "", fg = "#005ca5" },
	{ name = "cc", text = "", fg = "#f34b7d" },
	{ name = "ccm", text = "", fg = "#f34b7d" },
	{ name = "cfg", text = "", fg = "#6d8086" },
	{ name = "cjs", text = "", fg = "#cbcb41" },
	{ name = "clj", text = "", fg = "#8dc149" },
	{ name = "cljc", text = "", fg = "#8dc149" },
	{ name = "cljd", text = "", fg = "#519aba" },
	{ name = "cljs", text = "", fg = "#519aba" },
	{ name = "cmake", text = "", fg = "#dce3eb" },
	{ name = "cob", text = "", fg = "#005ca5" },
	{ name = "cobol", text = "", fg = "#005ca5" },
	{ name = "coffee", text = "", fg = "#cbcb41" },
	{ name = "conda", text = "", fg = "#43b02a" },
	{ name = "conf", text = "", fg = "#6d8086" },
	{ name = "config.ru", text = "", fg = "#701516" },
	{ name = "cow", text = "󰆚", fg = "#965824" },
	{ name = "cp", text = "", fg = "#519aba" },
	{ name = "cpp", text = "", fg = "#519aba" },
	{ name = "cppm", text = "", fg = "#519aba" },
	{ name = "cpy", text = "", fg = 
